# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs

# Build documentation using Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
