[project]
name = "rwslib"
version = "1.2.15"
description = "Rave Web Services for Python"
authors = [{ name = "Ian Sparks", email = "isparks@trialgrid.com" }]
requires-python = ">=3.8.0,<4"
readme = "README.md"
license = "MIT"
maintainers = [{ name = "Geoff Low", email = "geoff.low@3ds.com" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "lxml",
    "requests",
    "six",
    "click",
    "faker",
    "urllib3",
]

[project.urls]
Repository = "https://github.com/mdsol/rwslib"
Documentation = "https://rwslib.readthedocs.io"

[dependency-groups]
dev = [
    "httpretty",
    "mock",
    "coverage",
    "pytest",
    "tox",
]
docs = [
    "Sphinx>=6.0.0",
    "sphinx-pyproject>=0.3.0,<0.4",
]

[tool.uv]
default-groups = [
    "dev",
    "docs",
]

[tool.hatch.build.targets.sdist]
include = ["rwslib"]

[tool.hatch.build.targets.wheel]
include = ["rwslib"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.sphinx-pyproject]
project = "rwslib"
github_username = "mdsol"
github_repository = "rwslib"

