[tox]
envlist = clean, py{310,311,312}, anaconda3, coverage, stats
recreate = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    pytest tests --import-mode importlib
deps =
    pytest
    pytest-sugar
    mock
    httpretty


[testenv:coverage]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    coverage run -m pytest
deps =
    pytest
    pytest-sugar
    mock
    httpretty
    coverage

[testenv:clean]
allowlist_externals = poetry, coverage
commands=
    coverage erase

[testenv:stats]
allowlist_externals = poetry, coverage
commands=
    coverage report --include=rwslib/* --omit=*test*
    coverage html

[gh-actions]
python =
    3.10: py310, lint, manifest
    3.11: py311, lint, manifest
    3.12: py312, lint, manifest
    pypy3: pypy3

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]

[tool.coverage.report]
fail_under = 80

